// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcifhemwalxifhxxnjrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaWZoZW13YWx4aWZoeHhuanJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1OTMzMzcsImV4cCI6MjA2NzE2OTMzN30._n5uDZMHoVn-g5hN6-7N6ne_5hdR0L63oIn9qrNVPm8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});